### ISSUE TITLE
Add constraint on sysroot

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/libcufile-feedstock#26]
The fix for #23 in #24 was incomplete. In particular, 733742d0a153591ca37ac2b597616937a3b965e5 should be reverted. The failure can be seen in https://github.com/conda-forge/pytorch-cpu-feedstock/pull/299

```
+ pip check
No broken requirements found.
+ python -c 'import torch; torch.tensor(1).to('\''cpu'\'').numpy(); print('\''numpy support enabled!!!'\'')'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import torch; torch.tensor(1).to('cpu').numpy(); print('numpy support enabled!!!')
    ^^^^^^^^^^^^
  File "$PREFIX/lib/python3.13/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by $PREFIX/lib/python3.13/site-packages/torch/../../../././libcufile.so.0)
WARNING: Tests failed for pytorch-2.5.1-cuda126_py313hb62db30_205.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

CC @carterbox 

<details>
<summary>test environment</summary>

```
TEST START: /home/conda/feedstock_root/build_artifacts/linux-aarch64/pytorch-2.5.1-cuda126_py313hb62db30_205.conda
WARNING: Multiple meta files found. The meta.yaml file in the base directory (/tmp/tmp9b6ayz23/info/recipe) will be used.
Adding in variants from /tmp/tmp9b6ayz23/info/recipe/conda_build_config.yaml
Reloading output folder (local): ...working... done
Solving environment (_test_env): ...working... done

## Package Plan ##

  environment location: $PREFIX


The following NEW packages will be INSTALLED:

    _openmp_mutex:                 4.5-2_gnu                       conda-forge
    atk-1.0:                       2.38.0-hedc4a1f_2               conda-forge
    attr:                          2.5.1-h4e544f5_1                conda-forge
    attrs:                         24.2.0-pyh71513ae_0             conda-forge
    backports.zoneinfo:            0.2.1-py313hd81a959_9           conda-forge
    binutils_impl_linux-aarch64:   2.43-h4c662bb_2                 conda-forge
    binutils_linux-aarch64:        2.43-hf1166c9_2                 conda-forge
    boto3:                         1.35.74-pyhd8ed1ab_0            conda-forge
    botocore:                      1.35.74-pyge310_1234567_0       conda-forge
    brotli-python:                 1.1.0-py313hb6a6212_2           conda-forge
    bzip2:                         1.0.8-h68df207_7                conda-forge
    ca-certificates:               2024.8.30-hcefe29a_0            conda-forge
    cairo:                         1.18.0-hdb1a16f_3               conda-forge
    cffi:                          1.17.1-py313h2135053_0          conda-forge
    click:                         8.1.7-unix_pyh707e725_1         conda-forge
    colorama:                      0.4.6-pyhd8ed1ab_1              conda-forge
    cpython:                       3.13.0-py313hd8ed1ab_101        conda-forge
    cuda-cudart:                   12.6.77-h3ae8b8a_0              conda-forge
    cuda-cudart_linux-aarch64:     12.6.77-h3ae8b8a_0              conda-forge
    cuda-nvrtc:                    12.6.85-h5101a13_0              conda-forge
    cuda-nvtx:                     12.6.77-h5101a13_0              conda-forge
    cuda-version:                  12.6-h7480c83_3                 conda-forge
    cudnn:                         9.3.0.75-h125f736_1             conda-forge
    exceptiongroup:                1.2.2-pyhd8ed1ab_1              conda-forge
    expecttest:                    0.2.1-pyhd8ed1ab_0              conda-forge
    filelock:                      3.16.1-pyhd8ed1ab_1             conda-forge
    font-ttf-dejavu-sans-mono:     2.37-hab24e00_0                 conda-forge
    font-ttf-inconsolata:          3.000-h77eed37_0                conda-forge
    font-ttf-source-code-pro:      2.038-h77eed37_0                conda-forge
    font-ttf-ubuntu:               0.83-h77eed37_3                 conda-forge
    fontconfig:                    2.15.0-h8dda3cd_1               conda-forge
    fonts-conda-ecosystem:         1-0                             conda-forge
    fonts-conda-forge:             1-0                             conda-forge
    freetype:                      2.12.1-hf0a5ef3_2               conda-forge
    fribidi:                       1.0.10-hb9de7d4_0               conda-forge
    fsspec:                        2024.10.0-pyhff2d567_0          conda-forge
    gcc_impl_linux-aarch64:        12.4.0-hfb8d6db_1               conda-forge
    gcc_linux-aarch64:             12.4.0-heb3b579_7               conda-forge
    gdk-pixbuf:                    2.42.12-ha61d561_0              conda-forge
    gmp:                           6.3.0-h0a1ffab_2                conda-forge
    gmpy2:                         2.1.5-py313h0c041f1_2           conda-forge
    graphite2:                     1.3.13-h2f0025b_1003            conda-forge
    graphviz:                      12.0.0-h2a7c30b_0               conda-forge
    gtk2:                          2.24.33-h4cb56f0_5              conda-forge
    gts:                           0.7.6-he293c15_4                conda-forge
    gxx_impl_linux-aarch64:        12.4.0-h3c1ec91_1               conda-forge
    gxx_linux-aarch64:             12.4.0-h3f57e68_7               conda-forge
    h2:                            4.1.0-pyhd8ed1ab_1              conda-forge
    harfbuzz:                      9.0.0-hbf49d6b_1                conda-forge
    hpack:                         4.0.0-pyhd8ed1ab_1              conda-forge
    hyperframe:                    6.0.1-pyhd8ed1ab_1              conda-forge
    hypothesis:                    6.122.1-pyha770c72_0            conda-forge
    icu:                           75.1-hf9b3779_0                 conda-forge
    iniconfig:                     2.0.0-pyhd8ed1ab_1              conda-forge
    jinja2:                        3.1.4-pyhd8ed1ab_1              conda-forge
    jmespath:                      1.0.1-pyhd8ed1ab_1              conda-forge
    kernel-headers_linux-aarch64:  4.18.0-h05a177a_18              conda-forge
    ld_impl_linux-aarch64:         2.43-h80caac9_2                 conda-forge
    lerc:                          4.0.0-h4de3ea5_0                conda-forge
    libabseil:                     20240722.0-cxx17_h5ad3122_1     conda-forge
    libblas:                       3.9.0-25_linuxaarch64_openblas  conda-forge
    libcap:                        2.71-h51d75a7_0                 conda-forge
    libcblas:                      3.9.0-25_linuxaarch64_openblas  conda-forge
    libcublas:                     12.6.4.1-h5101a13_0             conda-forge
    libcufft:                      11.3.0.4-h5101a13_0             conda-forge
    libcufile:                     1.11.1.6-hd706c01_3             conda-forge
    libcurand:                     10.3.7.77-h5101a13_0            conda-forge
    libcusolver:                   11.7.1.2-h5101a13_0             conda-forge
    libcusparse:                   12.5.4.2-h5101a13_0             conda-forge
    libdeflate:                    1.22-h86ecc28_0                 conda-forge
    libexpat:                      2.6.4-h5ad3122_0                conda-forge
    libffi:                        3.4.2-h3557bc0_5                conda-forge
    libgcc:                        14.2.0-he277a41_1               conda-forge
    libgcc-devel_linux-aarch64:    12.4.0-h7b3af7c_101             conda-forge
    libgcc-ng:                     14.2.0-he9431aa_1               conda-forge
    libgcrypt-lib:                 1.11.0-h86ecc28_2               conda-forge
    libgd:                         2.3.3-h6818b27_10               conda-forge
    libgfortran:                   14.2.0-he9431aa_1               conda-forge
    libgfortran5:                  14.2.0-hb6113d0_1               conda-forge
    libglib:                       2.82.2-hc486b8e_0               conda-forge
    libgomp:                       14.2.0-he277a41_1               conda-forge
    libgpg-error:                  1.51-h05609ea_1                 conda-forge
    libiconv:                      1.17-h31becfc_2                 conda-forge
    libjpeg-turbo:                 3.0.0-h31becfc_1                conda-forge
    liblapack:                     3.9.0-25_linuxaarch64_openblas  conda-forge
    liblzma:                       5.6.3-h86ecc28_0                conda-forge
    liblzma-devel:                 5.6.3-h86ecc28_0                conda-forge
    libmagma:                      2.8.0-hfc09aae_0                conda-forge
    libmagma_sparse:               2.8.0-hfc09aae_0                conda-forge
    libmpdec:                      4.0.0-h68df207_0                conda-forge
    libnl:                         3.11.0-h86ecc28_0               conda-forge
    libnvjitlink:                  12.6.85-h5101a13_0              conda-forge
    libopenblas:                   0.3.28-pthreads_h9d3fd7e_1      conda-forge
    libpng:                        1.6.44-hc4a20ef_0               conda-forge
    libprotobuf:                   5.28.2-h029595c_0               conda-forge
    librsvg:                       2.58.4-h00090f3_0               conda-forge
    libsanitizer:                  12.4.0-h469570c_1               conda-forge
    libsqlite:                     3.47.0-hc4a20ef_1               conda-forge
    libstdcxx:                     14.2.0-h3f4de04_1               conda-forge
    libstdcxx-devel_linux-aarch64: 12.4.0-h7b3af7c_101             conda-forge
    libstdcxx-ng:                  14.2.0-hf1166c9_1               conda-forge
    libsystemd0:                   256.9-hd54d049_0                conda-forge
    libtiff:                       4.7.0-hec21d91_1                conda-forge
    libtorch:                      2.5.1-cuda126_h0f66eb2_205      local      
    libudev1:                      256.9-h86ecc28_0                conda-forge
    libuuid:                       2.38.1-hb4cce97_0               conda-forge
    libuv:                         1.49.2-h86ecc28_0               conda-forge
    libwebp-base:                  1.4.0-h31becfc_0                conda-forge
    libxcb:                        1.17.0-h262b8f6_0               conda-forge
    libxml2:                       2.13.5-hf4efe5d_0               conda-forge
    libzlib:                       1.3.1-h86ecc28_2                conda-forge
    lz4-c:                         1.9.4-hd600fc2_0                conda-forge
    markupsafe:                    3.0.2-py313h7815b11_1           conda-forge
    mock:                          5.1.0-pyhd8ed1ab_1              conda-forge
    mpc:                           1.3.1-h783934e_1                conda-forge
    mpfr:                          4.2.1-h2305555_3                conda-forge
    mpmath:                        1.3.0-pyhd8ed1ab_1              conda-forge
    nccl:                          2.23.4.1-h35f4307_3             conda-forge
    ncurses:                       6.5-hcccb83c_1                  conda-forge
    networkx:                      3.4.2-pyh267e887_2              conda-forge
    nomkl:                         1.0-h5ca1d4c_0                  conda-forge
    numpy:                         2.1.3-py313h97d08ae_0           conda-forge
    openssl:                       3.4.0-h86ecc28_0                conda-forge
    packaging:                     24.2-pyhd8ed1ab_2               conda-forge
    pango:                         1.54.0-h7579590_1               conda-forge
    pcre2:                         10.44-h070dd5b_2                conda-forge
    pip:                           24.3.1-pyh145f28c_0             conda-forge
    pixman:                        0.43.4-h2f0025b_0               conda-forge
    pluggy:                        1.5.0-pyhd8ed1ab_1              conda-forge
    pthread-stubs:                 0.4-h86ecc28_1002               conda-forge
    pycparser:                     2.22-pyh29332c3_1               conda-forge
    pydot:                         3.0.2-py313hd81a959_0           conda-forge
    pyparsing:                     3.2.0-pyhd8ed1ab_2              conda-forge
    pysocks:                       1.7.1-pyha55dd90_7              conda-forge
    pytest:                        8.3.4-pyhd8ed1ab_1              conda-forge
    python:                        3.13.0-h4f870b6_101_cp313       conda-forge
    python-dateutil:               2.9.0.post0-pyhff2d567_1        conda-forge
    python_abi:                    3.13-5_cp313                    conda-forge
    pytorch:                       2.5.1-cuda126_py313hb62db30_205 local      
    rdma-core:                     54.0-h1d056c8_1                 conda-forge
    readline:                      8.2-h8fc344f_1                  conda-forge
    s3transfer:                    0.10.4-pyhd8ed1ab_1             conda-forge
    setuptools:                    75.6.0-pyhff2d567_1             conda-forge
    six:                           1.16.0-pyhd8ed1ab_1             conda-forge
    sleef:                         3.7-h8fb0607_2                  conda-forge
    sortedcontainers:              2.4.0-pyhd8ed1ab_0              conda-forge
    sympy:                         1.13.3-pyh2585a3b_104           conda-forge
    sysroot_linux-aarch64:         2.17-h5b4a56d_18                conda-forge         # !!!!!!!!!
    tabulate:                      0.9.0-pyhd8ed1ab_1              conda-forge
    tk:                            8.6.13-h194ca79_0               conda-forge
    tomli:                         2.2.1-pyhd8ed1ab_1              conda-forge
    typing_extensions:             4.12.2-pyha770c72_1             conda-forge
    tzdata:                        2024b-hc8b5060_0                conda-forge
    urllib3:                       2.2.3-pyhd8ed1ab_1              conda-forge
    xmlrunner:                     1.7.7-py_0                      conda-forge
    xorg-libice:                   1.1.1-h57736b2_1                conda-forge
    xorg-libsm:                    1.2.4-hbac51e1_1                conda-forge
    xorg-libx11:                   1.8.10-hca56bd8_1               conda-forge
    xorg-libxau:                   1.0.11-h86ecc28_1               conda-forge
    xorg-libxdmcp:                 1.1.5-h57736b2_0                conda-forge
    xorg-libxext:                  1.3.6-h57736b2_0                conda-forge
    xorg-libxrender:               0.9.11-h57736b2_1               conda-forge
    xorg-xorgproto:                2024.1-h86ecc28_1               conda-forge
    xz:                            5.6.3-h2dbfc1b_0                conda-forge
    xz-gpl-tools:                  5.6.3-h2dbfc1b_0                conda-forge
    xz-tools:                      5.6.3-h86ecc28_0                conda-forge
    zlib:                          1.3.1-h86ecc28_2                conda-forge
    zstandard:                     0.23.0-py313h48a5650_1          conda-forge
    zstd:                          1.5.6-h02f22dd_0                conda-forge
```

</details>

**Comment by carterbox** [comment]
I am investigating this issue, and I have been able to reproduce the issue with the pytorch build locally. The next step that I am taking is to create a smaller reproducing example that doesn't require rebuilding the entirety of pytorch as this issue shouldn't be libcufile/pytorch specific.

My initial findings are that this issue only happens when cross-compiling as is currently done in the pytorch feedstock (building inside an aarch64 container using emulation is too slow). If building natively/emulated in our default containers, this is not a problem because the system glibc is the latest.

**Comment by carterbox** [comment]
I have written a debugging recipe (mentioned above) to reproduce this issue and adding a runtime constraint on the sysroot package did not solve the issue.

My vague (and possibly partly incorrect) understanding is that conda-build does not support testing cross-compiled packages natively. It only supports existence tests for those packages, so normally importing pytorch (which triggers the loading of libcufile) is not allowed. However, conda-forge does some extra things to automatically provide emulation for the test section of cross-compiled recipes.

Those extra things live in the conda-forge-ci-setup package in [cross_compile_support.sh](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/a5b25759400027c6343e13df44ad4828726a1724/recipe/cross_compile_support.sh). When I locally modified the `cross_compile_suport.sh` to set GLIBC_VERSION always to 2.34, the cross-compiled tests succeeded. This is because it is here in this script that the sysroot which the test-time emulator uses is created.

Looking at the logs of a cross-compile build, we see something like this:

```
++++ shyaml get-value c_stdlib_version.0 2.17
+++ GLIBC_VERSION=2.17
+++ HOST_PLATFORM=linux-aarch64
+++ CUDA_COMPILER_VERSION=None
+++ GLIBC_VERSION=2.17
+++ [[ linux-aarch64 != \l\i\n\u\x\-\6\4 ]]
+++ echo 'export CONDA_BUILD_CROSS_COMPILATION=1'
+++ export CONDA_BUILD_CROSS_COMPILATION=1
+++ CONDA_BUILD_CROSS_COMPILATION=1
+++ '[' -f /home/conda/feedstock_root/.ci_support/linux_aarch64_.yaml ']'
+++ echo build_platform:
+++ echo '- linux-64'
+++ [[ linux-64 == \l\i\n\u\x\-\6\4 ]]
+++ [[ linux-aarch64 == linux-* ]]
+++ mamba create -n sysroot_linux-aarch64 --yes --quiet sysroot_linux-aarch64=2.17
```

This is when the cross-compilation emulation environment is setup I guess? By default it uses shyaml to get the sysroot version from whatever has been set for c_stdlib_version. This is why cross-compiles fail but emulated/native builds succeed! Because for native/emulated builds, the sysroot during the test phase comes from the container which is defined by conda-forge.yml -> os_version, but the cross-compile sysroot comes from conda_build_config.

Furthermore, the cross-compile sysroot is set before conda-build starts, so we cannot control it from inside the recipe.

Therefore, I believe the solution is to choose the cross-compile sysroot based on the conda-forge.yml -> os_version so that is consistent with non-cross-compile builds.

**Comment by h-vetinari** [comment]
Thanks for debugging this. I'm happy to close this as fixed by https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/368 (which was an aspect of the whole setup I hadn't fully grasped yet).
